### ISSUE TITLE
Fish configuration example

### ISSUE THREAD

**Issue by Luzifer** [vinceprignano/gocd#1]
As a user of the fish-shell I built a small (and probably) ugly workaround to have the same behavior in fish as you built in `shellinit` (except the autocompletion). Maybe you want to add it as an example how to get the auto-cd to work in fish:

```
~> cat ./config/fish/functions/gocd.fish
function gocd
  if set dir (eval $GOPATH/bin/gocd $argv)
    cd $dir
  else
    eval $GOPATH/bin/gocd $argv
  end
end
~>
```

**Comment by vincepri** [comment]
Thanks! :)
